#!/bin/sh /etc/rc.common

#https://openwrt.org/docs/guide-developer/procd-init-script-example

USE_PROCD=1
 
START=95
STOP=01

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "/usr/bin/okmonitor-listen-commands"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/okmonitor-listen-commands.pid
    procd_close_instance
}

stop_service()
{
	PID=$(cat /var/run/okmonitor-listen-commands.pid)
	pkill -9 -P $PID
}
