#!/bin/sh /etc/rc.common

#https://openwrt.org/docs/guide-developer/procd-init-script-example

USE_PROCD=1

START=95
STOP=01
 
start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "/usr/bin/okmonitor-broadcast"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/okmonitor-broadcast.pid
    procd_close_instance
}

restart_service() {
	stop_service
	sleep 5
	start_service
}

stop_service() {
	PID=$(cat /var/run/okmonitor-broadcast.pid)
	pkill -9 -P $PID
	screen -S screen_1 -p screen_1  -X kill
	screen -S screen_2 -p screen_2  -X kill
	screen -S screen_3 -p screen_3  -X kill
	screen -S screen_4 -p screen_4  -X kill
#	killall -9 ffmpeg
}
